### ISSUE TITLE
Router suggestion

### ISSUE THREAD

**Issue by MartinsThiago** [Polymer/project#11]
As polymer team is working on a router solution, we could have a `router behavior`. This could turn development more flexible

**Comment by tjsavage** [comment]
Could you elaborate a bit on what you're looking for with a `router behavior`?

**Comment by MaciejHanajczyk** [comment]
I think a standard iron-router element and a router behavior would be perfect.
When can expect some preview versions?

**Comment by MeTaNoV** [comment]
https://github.com/PolymerLabs/lab-elements

**Comment by abdonrd** [comment]
https://github.com/PolymerElements/carbon-route

Maybe we can close. :)

**Comment by MaciejHanajczyk** [comment]
Ok

2016-04-28 16:01 GMT+02:00 Abdón Rodríguez Davila <notifications@github.com>
:

**Comment by MartinsThiago** [comment]
Whoops, sorry
closing...
