### ISSUE TITLE
Polymer 2.x

### ISSUE THREAD

**Issue by max-voloshin** [Polymer/project#23]
Hi guys!

Are there any plans to release the new major version (non compatible) in 2016? Our team evaluates migration from 0.5 to 1.x and worries about further upgrade newer versions.

Much appreciate your answers.

**Comment by ebidel** [comment]
@tjsavage ^

**Comment by tjsavage** [comment]
We do plan to release a new major version in the second half of this year, but the aim is to keep it fully-compatible or near-compatible with 1.x. The evolutions for a 2.0 will be:

- Making it compatible with the latest v1 versions of the Custom Elements and Shadow DOM specs, especially as all major browsers are now looking to ship these specs.
- Pulling out individual features that Polymer provides into individual, granular libraries, as [described in the roadmap](https://github.com/Polymer/project/blob/master/Roadmap.md#core-polymer-library)
- Building an overarching wrapper layer that pulls together these features, with the aim of being as compatible with Polymer 1.x as possible.

So all-in-all it will be a minimal breaking change for future-proof platform compatibility, as well as optionally a feature-driven pay-as-you-go model for building re-usable components.

**Comment by max-voloshin** [comment]
Looks very promising! Thanks for your reply! Feel free to close this "issue" :)

**Comment by sergicontre** [comment]
Great!!!

**Comment by tjsavage** [comment]
Sure thing! Of course, we'll keep updates coming as we near a preview of the release.
