### ISSUE TITLE
Is the polymer-project.org website seriously broken?

### ISSUE THREAD

**Issue by kpgarrod** [Polymer/project#27]
![polymer-project screenshot](https://cloud.githubusercontent.com/assets/2155409/17174092/30d799d2-53ff-11e6-8ac6-6b691e12edbe.png)

It looks broken and links don't work.

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1688

**Comment by kpgarrod** [comment]
@ebidel Yes it was Polymer dev tools extension - I should have read the review before installing it, thanks for responding.
