### ISSUE TITLE
Polymer Project Plan

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/project#31]
Is there any News what the plan for polymer is?
we have now webcomponents v1, will&when polymer support it? whats going on with the designer? ....
would be nice if there would be a few more blogposts what will & happens to polymer.

**Comment by tjsavage** [comment]
A major update here - we recently announced Polymer 2.0: https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0.html

**Comment by jogibear9988** [comment]
about 2.0? Is there a time schedule when it's planed to be released?

**Comment by MeTaNoV** [comment]
@tjsavage THAT was a NICE SUR-PRISE !!! THX to ALL DA TEAM! I will update my set of components using: https://www.polymer-project.org/2.0/docs/about_20#upgrading

**Comment by tjsavage** [comment]
We're currently aiming to release 2.0 very early next year.

**Comment by MeTaNoV** [comment]
@tjsavage thanks and good job!! I will support the best I can!!

**Comment by jogibear9988** [comment]
Again, a update of the current state would be nice? I would like if the develop process would be more open. I know we could see everything on github, but I'd like if there would be a blog with weekly news etc... There are months with no news from polymer :-(
And also a update to the designer state would be nice, even when there is nothing new, maybe you can tell if you still have plans for it.

**Comment by tjsavage** [comment]
Hey @jogibear9988 - https://www.polymer-project.org/1.0/blog/2016-12-21-polymer-2.0-update.html was our most recent major update. We're currently anticipating a release candidate for 2.0 in ~2 weeks and a stable release by March.

Designer is still on-hold until at least Polymer 2.0 is stable. We do still have plans for it, but status has not changed. We'll definitely update on the blog when we have something here.

**Comment by jogibear9988** [comment]
Thanks for the Info. I know the blog post from december, I only want to say, it would be nice if there is a little more communication, so people see whats going on. Maybe like a weekly status update, or a weekly tweet.

**Comment by tjsavage** [comment]
Definitely - this is something we're actively working on getting better at. Thanks for the note.

**Comment by abdonrd** [comment]
I'm totally agree. I understand that it can be complicated, but it would be great if there was a more constant communication.

If you don't follow the project very closely, it gives the impression that it is very still.

**Comment by jogibear9988** [comment]
NEWS ? ;-)

**Comment by jogibear9988** [comment]
No News? Would realy be interesting to know where we are? When can we estimate first release?

**Comment by arthurevans** [comment]
Since 2.0 is release, and there's another issue open to update the roadmap, I'm going to close this one.
