### ISSUE TITLE
polymer-project.org crashes FF50 android

### ISSUE THREAD

**Issue by thewhitetulip** [Polymer/project#33]
I opened polymer-project.org ten times on firefox for mobile(android) version 50. The browser crashed all of the time.

The shop.polymer-project.org works perfectly fine though.

Apologies if this is not the right place for this issue, but did not know where else to raise it

**Comment by tjsavage** [comment]
Hm I'm not able to reproduce this - please comment again if you're still running into this and we can re-open.

**Comment by thewhitetulip** [comment]
Does not crash now
