### ISSUE TITLE
What are the plans with dependency management?

### ISSUE THREAD

**Issue by froucher** [Polymer/project#37]
There's a confusing message in bower repository (https://github.com/bower/bower)

> ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

So, what are the plans with dependency management?

Thanks

**Comment by abdonrd** [comment]
Some references:

* https://github.com/Polymer/polymer/issues/326#issuecomment-303148878
* https://github.com/Polymer/polymer/issues/326#issuecomment-306239757

**Comment by arthurevans** [comment]
Plans to support the npm registry were announced at Polymer Summit 2017. See the summary here: https://www.polymer-project.org/blog/2017-08-22-npm-modules.html

Please check back on the blog and/or join on on our Slack channels (visit https://polymer-slack.herokuapp.com/ to join) for future announcements.
