### ISSUE TITLE
Polymer - official developer library of the web platform at Google

### ISSUE THREAD

**Issue by cosminnicula** [Polymer/project#5]
At the 2015 Polymer Summit, Taylor Savage mentioned in the Opening Keynote that: "We (Polymer) are the official developer library of the web platform at Google" https://www.youtube.com/watch?v=jVn8tlnwAEs&t=1m18s

Given that some of Polymer's features (e.g. component model, router etc.) overlaps with Angular's features, is there an official statement in regards to what Angular is for Google and whether or not Google will continue to support both of them even though these two products are heading different directions?

**Comment by tjsavage** [comment]
Hey @cosminnicula thanks for the question. 

First just a quick clarification: The Polymer library refers to just the sugaring layer on top of web components, that makes it easy to build elements. The router we're working on is an element built with the library and not part of the library itself. The goal with web components at its core is interoperability - one should be able to use anything built with Polymer with any framework that knows about DOM. This is 100% true yet under the web component polyfills, though we're working to make it more seamless. That said, there's a really compelling story around actually building an entire application just out of components, and so we're working to make it clearer how to achieve this with things like a routing element.

"Official library of the web platform at Google" refers to that the Polymer library is built, maintained, and recommended by the Web Platform group at Google, which sits within the Chrome organization. The Web Platform team also builds much of the guts of Chrome, like the Blink engine. Polymer is developed very purposefully to be directly complementary to the web platform itself, and so is the web platform team at Google's officially supported web developer library for building components. There are many different web developer tools that have come from Google - Angular, Closure, etc. - but Polymer is the library that is being actively built and grown by Google's Web Platform team.

Re: Polymer and Angular, I can't speak directly to the Angular team's goals, though I have no doubt the framework will continue to be supported. It's an incredibly expansive framework with massive adoption, and a platform unto itself.

For the Google Web Platform team though, the platform is the web platform itself, Web Components form the component model, and Polymer is the library that makes it easy to leverage this component model.

I hope that answers your question a bit - please feel free to re-open if not!
