### ISSUE TITLE
What is the best practice to deal with component with bunch of css

### ISSUE THREAD

**Issue by yurychika** [Polymer/project#6]
I am now working on a component. Actually it's a transform from old dojo widget to Polymer web component. Everything works as expected and really appreciate your hard working to make it happen.

The tricky part is that the initial dojo widget tends to have lots of css. There is a single entry for the css file inside which there is a couple of css @import to reference css from other places. For this scenario, the easy for me to handle this would be <link> a reference to the css entry, but this is deprecated according to the polymer's document about external stylesheets.  When trying to use the shared stylesheet which is recommended, I found it very ugly and inconvenient to insert a huge amount of css inside a single html for css-import.

I wonder if there could be a better solution for this? I know I can create a css import h html for each of the css files and then import those css into a single css html as the entry, but I am not sure if it's the right thing to do.

And also, how to use LESS to write css for polymer component? I think if I want to use them together, maybe I will need to do some stuff on my own like suffixing & prefixing the compile css and wrap it in an html for css import.

Thanks for the help and hope I have made myself clear.

**Comment by robdodson** [comment]
My understanding is when custom properties ship everywhere you should be able to just use external stylesheets again, in the meantime we have to polyfill with html files. We used to allow CSS files but if I recall, the way we were parsing them to polyfill custom properties was actually a bit of a security "no-no." @sorvell would know more of the backstory on that.

IMO, it doesn't seem that dissimilar to put CSS in an external stylesheet or inside a style tag in an external HTML file if that's the only content in the files. Really the only the difference then is a file extension and a style tag.

For using LESS, you could write a gulp task to compile LESS to a .css file, then rename it to .html and wrap the contents in a style tag.

**Comment by yurychika** [comment]
@robdodson Thanks for the reply. 
I agree your opinion about external stylesheets and external HTML file. Maybe another big difference is that current external stylesheets is still for global stylesheets and couldn't apply solely for shadow DOM while our external html can.
